### ISSUE TITLE
Multiple values for parameters are not honored

### ISSUE THREAD

**Issue by DiomedeaExulans** [andrew-canaday/libvmod-queryfilter#2]
For parameter names that appear multiple times in a query string and are passed in using `name[]=` format, `queryfilter` honors only the last value that was provided.

With VCL set to:
```
queryfilter.filterparams("a[],a%5B%5D");
```
And a request in the form of:
```
?a%5B%5D=1&a%5B%5D=2
```
The parsed query string is:
```
a%5B%5D=2
```
The expected parsed query string is:
```
a%5B%5D=1&a%5B%5D=2
```

**Comment by andrew-canaday** [comment]
This should be resolved in *v0.1.0*.
