### ISSUE TITLE
filterparams requires param to be provided in a single line

### ISSUE THREAD

**Issue by DiomedeaExulans** [andrew-canaday/libvmod-queryfilter#3]
The second parameter for `filterparams()` is a comma-separated list of values that must be provided in a single line. When the list of values is long, it makes for a long line of code:
```
set req.url = queryfilter.filterparams(req.url, "firstparam,secondparam,thirdparam,fourthparam,fifthparam,sixthparam");
```
It would be nice to be able to split that line up for readability/maintainability, such as:
```
set req.url = queryfilter.filterparams(req.url,
    "firstparam" + queryfilter.separator() +
    "secondparam" + queryfilter.separator() +
    "thirdparam" + queryfilter.separator() +
    "fourthparam" + queryfilter.separator() +
    "fifthparam" + queryfilter.separator() +
    "sixthparam" + queryfilter.separator()
);
```

**Comment by andrew-canaday** [comment]
I'll consider updating the interface in the next major release. In the meantime, however, you can use VLC's '+' operator like so:
```
set req.url = queryfilter.filterparams(req.url,
    "firstparam," +
    "secondparam," +
    "thirdparam," +
    "fourthparam," +
    "fifthparam," +
    "sixthparam" +
);
```

**NOTE:** This _does waste a small amount of CPU performing the concatenation_, but it's likely you won't really notice.

**Comment by DiomedeaExulans** [comment]
Ah, I tried standard string concatenation in the VCL a while ago, but it didn't work for me -- I must have been doing something wrong. No need to update the VMOD when VCL provides a solution. Thanks!
