### ISSUE TITLE
varnish 4.X support?

### ISSUE THREAD

**Issue by zygis** [andrew-canaday/libvmod-queryfilter#4]

**Comment by andrew-canaday** [comment]
I should have a little time today to get this started. I'll post back with an estimated release date later. Thanks for you interest.

-Andrew

**Comment by zygis** [comment]
Any updates on this?

**Comment by andrew-canaday** [comment]
Apologies for the delay. Making some time to wrap this up. _Best case_, it'll be released this weekend; worst case, I'll cut the release next Friday (4/15). :)

**Comment by andrew-canaday** [comment]
Better late than never. It's pushed. More docs forthcoming.
